# Generated by Django 4.1.3 on 2022-11-12 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('customer', 'customer'), ('maid', 'maid')], default='customer', max_length=30)),
                ('adhar', models.IntegerField(blank=True, null=True)),
                ('mobile_number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('work_type', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
