# Generated by Django 3.0.5 on 2022-11-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaidUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('adhar', models.IntegerField(blank=True, null=True)),
                ('mobile_number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
