# Generated by Django 3.0.5 on 2022-11-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0002_auto_20221113_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maiduserprofile',
            name='adhar',
        ),
    ]
