# Generated by Django 3.0.5 on 2022-11-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0003_remove_maiduserprofile_adhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maiduserprofile',
            name='mobile_number',
            field=models.CharField(max_length=30),
        ),
    ]
