# Generated by Django 4.1.3 on 2022-11-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maidapp', '0004_auto_20221113_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='maiduserprofile',
            name='monthly_Charge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='maiduserprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
